### ISSUE TITLE
Error when using method 4

### ISSUE THREAD

**Issue by qaq2423349506** [PKULCWM/PKUSUMSUM#10]
java -jar PKUSUMSUM.jar -T 1 -input content200.txt -output sum.txt -L 1 -n 7 -m 4 -stop n

Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at code.Run.main(Run.java:192)
	... 6 more

**Comment by victorwsl** [comment]
I encountered the same error. Did you find out the solution?

**Comment by roncking** [comment]
The -output parameter needs to include a folder name, like outputdir\sum.txt. The getparent call is failing because it's expecting a parent folder, not just a file name.
