### ISSUE TITLE
error about file

### ISSUE THREAD

**Issue by leisurehippo** [PKULCWM/PKUSUMSUM#11]
命令java -jar PKUSUMSUM.jar -T 1 -input article_didi.txt -output summay.txt -L 1 -n 20 -m 2 -stop n
报错如下
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at com.simontuffs.onejar.Boot.run(Boot.java:306)
        at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.lang.NullPointerException
        at java.io.File.<init>(Unknown Source)
        at code.Run.main(Run.java:192)
        ... 6 more

这个是什么原因造成的呢？多谢

**Comment by zshtom** [comment]
-output /dirname/test.txt 这样 就可以了 输出是需要一个文件名的
