### ISSUE TITLE
Error when using type 1 language 2 method 3

### ISSUE THREAD

**Issue by junhua** [PKULCWM/PKUSUMSUM#4]
> java -jar PKUSUMSUM.jar -T 1 -input ./samples/article.txt -output ./samples/summary3.txt -L 2 -n 500 -m 3 -stop n

```
JarClassLoader: Warning: Unable to load native library: java.lang.NullPointerException
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.simontuffs.onejar.Boot.run(Boot.java:306)
    at com.simontuffs.onejar.Boot.main(Boot.java:159)
Caused by: java.lang.UnsatisfiedLinkError: no lpsolve55j in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at lpsolve.LpSolve.<clinit>(LpSolve.java:275)
    at code.ILP.execute(ILP.java:225)
    at code.ILP.Summarize(ILP.java:90)
    at code.Run.main(Run.java:329)
    ... 6 more

```

**Comment by sodawater** [comment]
Sorry for replying you so late. I run the same parameter as you do and I get the same "JarClassLoader: Warning". But it didn't prompt the Exception. 
"-m 3" means that you choose the ILP method.  It seems that you have not copied the lpsolve55.dll dynamic libraries correctly. You can refer to the Notice in README and it may help you.

**Comment by sodawater** [comment]
Sorry for replying you so late. I run the same parameter as you do and I get the same "JarClassLoader: Warning". But it didn't prompt the Exception.
"-m 3" means that you choose the ILP method. It seems that you have not copied the lpsolve55.dll dynamic libraries correctly. You can refer to the Notice in README and it may help you.
