### ISSUE TITLE
report error in centroid method

### ISSUE THREAD

**Issue by lipiji** [PKULCWM/PKUSUMSUM#8]
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at code.MEAD.Summarize(MEAD.java:106)
	at code.Run.main(Run.java:324)
	... 6 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.simontuffs.onejar.Boot.run(Boot.java:306)
	at com.simontuffs.onejar.Boot.main(Boot.java:159)

**Comment by PKULCWM** [comment]
what's your specific parameter?
It seems that the length of the input file is too long and might be out of limit. If so, you may have to wait for some time. We are working on this problem and it will be solved in next version. 
Sorry for this error.
